ALTER TABLE therapy_aliases DROP CONSTRAINT therapy_aliases_concept_id_fkey;
ALTER TABLE therapy_trade_names DROP CONSTRAINT therapy_trade_names_concept_id_fkey;
ALTER TABLE therapy_xrefs DROP CONSTRAINT therapy_xrefs_concept_id_fkey;
ALTER TABLE therapy_associated_with DROP CONSTRAINT therapy_associated_with_concept_id_fkey;
