# flake8: noqa
"""Create tables

Revision ID: 05a8e608b181
Revises:
Create Date: 2020-10-29 09:00:11.484671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a8e608b181'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_data',
        sa.Column('src_name', sa.String(), nullable=False),
        sa.Column('data_license', sa.String(), nullable=False),
        sa.Column('data_license_url', sa.String(), nullable=False),
        sa.Column('version', sa.String(), nullable=False),
        sa.Column('data_url', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('src_name')
        )
        op.create_table('therapies',
        sa.Column('concept_id', sa.String(), nullable=False),
        sa.Column('label', sa.String(), nullable=True),
        sa.Column('max_phase', sa.Integer(), nullable=True),
        sa.Column('withdrawn_flag', sa.Boolean(), nullable=True),
        sa.Column('src_name', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['src_name'], ['meta_data.src_name'], ),
        sa.PrimaryKeyConstraint('concept_id')
    )
    with op.batch_alter_table('therapies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_therapies_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_therapies_label'), ['label'], unique=False)
        batch_op.create_index('lower_therapies_c_id', [sa.text('lower(concept_id)')], unique=False)
        batch_op.create_index('lower_therapies_label', [sa.text('lower(label)')], unique=False)

    op.create_table('aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('concept_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['therapies.concept_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aliases_alias'), ['alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_aliases_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index('lower_alias', [sa.text('lower(alias)')], unique=False)

    op.create_table('other_identifiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concept_id', sa.String(), nullable=True),
    sa.Column('other_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['therapies.concept_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('other_identifiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_other_identifiers_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_other_identifiers_other_id'), ['other_id'], unique=False)
        batch_op.create_index('lower_other_identifiers_c_id', [sa.text('lower(concept_id)')], unique=False)

    op.create_table('trade_names',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_name', sa.String(), nullable=False),
    sa.Column('concept_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['therapies.concept_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_names', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_names_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_names_trade_name'), ['trade_name'], unique=False)
        batch_op.create_index('lower_trade_name', [sa.text('lower(trade_name)')], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_names', schema=None) as batch_op:
        batch_op.drop_index('lower_trade_name')
        batch_op.drop_index(batch_op.f('ix_trade_names_trade_name'))
        batch_op.drop_index(batch_op.f('ix_trade_names_concept_id'))

    op.drop_table('trade_names')
    with op.batch_alter_table('other_identifiers', schema=None) as batch_op:
        batch_op.drop_index('lower_other_identifiers_c_id')
        batch_op.drop_index(batch_op.f('ix_other_identifiers_other_id'))
        batch_op.drop_index(batch_op.f('ix_other_identifiers_concept_id'))

    op.drop_table('other_identifiers')
    with op.batch_alter_table('aliases', schema=None) as batch_op:
        batch_op.drop_index('lower_alias')
        batch_op.drop_index(batch_op.f('ix_aliases_concept_id'))
        batch_op.drop_index(batch_op.f('ix_aliases_alias'))

    op.drop_table('aliases')
    with op.batch_alter_table('therapies', schema=None) as batch_op:
        batch_op.drop_index('lower_therapies_label')
        batch_op.drop_index('lower_therapies_c_id')
        batch_op.drop_index(batch_op.f('ix_therapies_label'))
        batch_op.drop_index(batch_op.f('ix_therapies_concept_id'))

    op.drop_table('therapies')
    op.drop_table('meta_data')
    # ### end Alembic commands ###
